In [2]:
import numpy as np

In [6]:
# help(np.array)

## 1.创建ndarray

In [ ]:
# Numpy库中的矩阵模块为ndarray对象,即N维数组对象，d指的是 dimension ，维度

In [4]:
##一维

In [11]:
a=np.array([1.1,2,3,4])

In [12]:
#属性：ndim(维度)，dtype(元素数据类型)，shape(数组的形状)，size(数组的元素总个数)

In [13]:
a

array([ 1.1,  2. ,  3. ,  4. ])

In [14]:
a.ndim

1

In [15]:
a.dtype

dtype('float64')

In [16]:
b=np.array([
        [1,2,3,4],
        [2,3,4,5]
    ])

In [17]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [18]:
b.ndim

2

In [19]:
b.dtype

dtype('int32')

In [24]:
c=np.array([
        [
            [1.1,2,3,4],
            [2,3,4,5]
        ],
        [
           [10,20,30,40],
           [20,30,40,50]
        ]
    ])

In [25]:
c

array([[[  1.1,   2. ,   3. ,   4. ],
        [  2. ,   3. ,   4. ,   5. ]],

       [[ 10. ,  20. ,  30. ,  40. ],
        [ 20. ,  30. ,  40. ,  50. ]]])

In [26]:
c.ndim

3

In [27]:
c.dtype

dtype('float64')

In [28]:
##数组的形状：不同维度下的数量

In [29]:
b.shape

(2, 4)

In [30]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [31]:
c

array([[[  1.1,   2. ,   3. ,   4. ],
        [  2. ,   3. ,   4. ,   5. ]],

       [[ 10. ,  20. ,  30. ,  40. ],
        [ 20. ,  30. ,  40. ,  50. ]]])

In [32]:
b.size

8

In [34]:
c.size   #元素总个数，shape值相乘得到

16

## 通过函数创建

In [36]:
a1=np.zeros((3,2))   #创建数组，指定形状，数值由零去填充

In [37]:
a1.ndim

2

In [38]:
a1

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [39]:
a1=np.ones((4,2))   #创建数组，指定形状，数值由一去填充

In [40]:
a1

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [41]:
a1.dtype

dtype('float64')

In [50]:
a2=np.empty((3,2))   #创建数组，指定形状，数值由未初始化过的垃圾值去填充

In [51]:
a2

array([[  8.05753836e-315,   8.05753820e-315],
       [  8.05675157e-315,   9.29012033e-312],
       [  9.28959661e-312,   9.28959660e-312]])

## 通过函数计算的方式去创建数组

In [ ]:
# range(start, end, step)，返回一个list对象，起始值为start，终止值为end，但不含终止值，步长为step。只能创建int型list。
# arange(start, end, step)，与range()类似，但是返回一个array对象。需要引入import numpy as np，并且arange可以使用float型数据。

In [52]:
#arange     linspace      logspace

In [53]:
np.arange(20)    #区间：左闭右开；  只写一个参数，终止值。默认起始值为0，步长为1.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
np.arange(10,20)    #区间：左闭右开；  写两个参数，起始值，终止值。默认步长为1.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
np.arange(10,20,2)  #区间：左闭右开；  参数，起始值，终止值，步长

array([10, 12, 14, 16, 18])

In [56]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [57]:
np.linspace(0,10,5)   #区间：全闭；参数：起始值，终止值，元素个数。等差数列。

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [58]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [59]:
np.logspace(0,2,5)  #区间：全闭；参数：起始值(以10为底，n次方)，终止值（以10为底，n次方），元素个数。等比数列。 

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [60]:
help(np.logspace)

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base of 

## 索引

In [61]:
arr=np.array([
        [
            [1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]
        ],
        [
            [10,20,30,40],
            [20,30,40,50],
            [30,40,50,60]
        ]
    ])

In [62]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60]]])

In [63]:
arr[1]

array([[10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60]])

In [64]:
arr[1][1]

array([20, 30, 40, 50])

In [65]:
arr[1][1][2]

40

In [66]:
arr[1,1,2]=99

In [67]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 99, 50],
        [30, 40, 50, 60]]])

In [68]:
import numpy as np

In [69]:
arr=np.array([
        [
            [1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]
        ],
        [
            [10,20,30,40],
            [20,30,40,50],
            [30,40,50,60]
        ]
    ])

In [70]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60]]])

In [71]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60]]])

In [72]:
arr[1]

array([[10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60]])

In [73]:
arr[1][0]

array([10, 20, 30, 40])

In [74]:
arr[1][0][1]

20

In [75]:
arr[1][0][2]

30

In [76]:
arr[1][0][1:3]    #左闭右开

array([20, 30])

In [77]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60]]])

In [79]:
arr[1][0][1:]
arr[1][0][1:4]

array([20, 30, 40])

In [80]:
arr[1,:,1:3]     #冒号在维度上，表示保留该维度的所有数据，，，冒号出现在区间内，[)

array([[20, 30],
       [30, 40],
       [40, 50]])

In [81]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60]]])

In [83]:
arr1=arr[1,:,1:3] 

In [84]:
arr1

array([[20, 30],
       [30, 40],
       [40, 50]])

In [86]:
arr1[1,0]=99   #numpy里面的切片组数，只是原来数组的一个视图，对于新数组的修改，原数组也会生效

In [87]:
arr1

array([[20, 30],
       [99, 40],
       [40, 50]])

In [88]:
arr

array([[[ 1,  2,  3,  4],
        [ 2,  3,  4,  5],
        [ 3,  4,  5,  6]],

       [[10, 20, 30, 40],
        [20, 99, 40, 50],
        [30, 40, 50, 60]]])

## numpy 的布尔索引

In [3]:
A=np.random.random((4,4))

In [4]:
A

array([[ 0.97554975,  0.52995428,  0.65158493,  0.97176847],
       [ 0.30959293,  0.99199081,  0.77564743,  0.03955585],
       [ 0.47718574,  0.53074277,  0.90298895,  0.67534879],
       [ 0.6736642 ,  0.33164172,  0.83960765,  0.78145619]])

In [5]:
A<0.5

array([[False, False, False, False],
       [ True, False, False,  True],
       [ True, False, False, False],
       [False,  True, False, False]], dtype=bool)

In [6]:
A[A<0.5]

array([ 0.30959293,  0.03955585,  0.47718574,  0.33164172])

In [7]:
names=np.array(['Gerry','Tom','John'])
scores=np.array([
        [98,87,76,65],
        [45,45,66,90],
        [87,76,67,91]
    ])


In [9]:
classs=np.array([u'语文',u'数学',u'英语',u'体育'])
names=='Gerry'

array([ True, False, False], dtype=bool)

In [13]:
print("Gerry score is :",scores[names=='Gerry'].reshape((-1)))

('Gerry score is :', array([98, 87, 76, 65]))


In [103]:
print("Gerry score is :",scores[names=='Gerry'].reshape((-1))[classs==u'数学'])

Gerry score is : [87]


In [105]:
print(u'Gerry和Tom的成绩')
print(scores[(names=='Gerry')|(names=='Tom')])

Gerry和Tom的成绩
[[98 87 76 65]
 [45 45 66 90]]


In [106]:
print(u'非Gerry和Tom的成绩')
print(scores[(names!='Gerry')&(names!='Tom')])

非Gerry和Tom的成绩
[[87 76 67 91]]


In [107]:
### numpy 中不能使用and,or,not,,,&|~

## ndarray的花式索引

In [109]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
arr[[0,3,5]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [111]:
arr[[0,3,5],[0,3,2]]   #直接传列表：按照对应维度位置提取一个值

array([ 0, 15, 22])

In [112]:
arr[np.ix_([0,3,5],[0,3,2])]   #ix_索引器：分别去拿对应维度上面的对应位置数据

array([[ 0,  3,  2],
       [12, 15, 14],
       [20, 23, 22]])

In [113]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [114]:
arr.shape

(8, 4)

In [115]:
arr1=arr.transpose()

In [116]:
arr1

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [117]:
arr1.shape

(4, 8)

In [118]:
arr=np.array([
        [
            [1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]
        ],
        [
            [10,20,30,40],
            [20,30,40,50],
            [30,40,50,60]
        ]
    ])

In [119]:
arr.shape

(2, 3, 4)

In [120]:
arr2=arr.T      #transpose和T都是转置

In [121]:
arr2

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 2, 20],
        [ 3, 30],
        [ 4, 40]],

       [[ 3, 30],
        [ 4, 40],
        [ 5, 50]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]]])

In [122]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
arr[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23],
       [24, 26, 27],
       [28, 30, 31]])