- [Imputer](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Imputer.html#sklearn.preprocessing.Imputer)

In [1]:
import numpy as np
from sklearn.preprocessing import Imputer

In [2]:
X = [
    [2, 2, 4, 1],
    [np.nan, 3, 4, 4],
    [1, 1, 1, np.nan],
    [2, 2, np.nan, 3]
]
X2 = [
    [2, 6, np.nan, 1],
    [np.nan, 5, np.nan, 1],
    [4, 1, np.nan, 5],
    [np.nan, np.nan, np.nan, 1]
]

In [3]:
# 缺失值填充
imp1 = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp2 = Imputer(missing_values='NaN', strategy='mean', axis=1) # 列填充？不是行
imp1.fit(X)
imp2.fit(X)

Imputer(axis=1, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [4]:
print (imp1.transform(X2))
print ("--------------------------")
print (imp2.transform(X2))

[[ 2.          6.          3.          1.        ]
 [ 1.66666667  5.          3.          1.        ]
 [ 4.          1.          3.          5.        ]
 [ 1.66666667  2.          3.          1.        ]]
--------------------------
[[ 2.          6.          3.          1.        ]
 [ 3.          5.          3.          1.        ]
 [ 4.          1.          3.33333333  5.        ]
 [ 1.          1.          1.          1.        ]]


In [5]:
imp1 = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp2 = Imputer(missing_values='NaN', strategy='median', axis=0)
imp3 = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp1.fit(X)
imp2.fit(X)
imp3.fit(X)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)

In [6]:
print (X2)
print ("--------------------------")
print (imp1.transform(X2))
print ("--------------------------")
print (imp2.transform(X2))
print ("--------------------------")
print (imp3.transform(X2))

[[2, 6, nan, 1], [nan, 5, nan, 1], [4, 1, nan, 5], [nan, nan, nan, 1]]
--------------------------
[[ 2.          6.          3.          1.        ]
 [ 1.66666667  5.          3.          1.        ]
 [ 4.          1.          3.          5.        ]
 [ 1.66666667  2.          3.          1.        ]]
--------------------------
[[ 2.  6.  4.  1.]
 [ 2.  5.  4.  1.]
 [ 4.  1.  4.  5.]
 [ 2.  2.  4.  1.]]
--------------------------
[[ 2.  6.  4.  1.]
 [ 2.  5.  4.  1.]
 [ 4.  1.  4.  5.]
 [ 2.  2.  4.  1.]]


In [7]:
import numpy as np
from numpy import random

In [8]:
x=random.RandomState(1)
0.5-x.rand(14)

array([ 0.082978  , -0.22032449,  0.49988563,  0.19766743,  0.35324411,
        0.40766141,  0.31373979,  0.15443927,  0.10323253, -0.03881673,
        0.08080549, -0.1852195 ,  0.29554775, -0.37811744])