In [9]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [10]:
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
poly1 = PolynomialFeatures(2)
poly1.fit(X)
print poly1
print poly1.transform(X)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False)
[[  1.   0.   1.   0.   0.   1.]
 [  1.   2.   3.   4.   6.   9.]
 [  1.   4.   5.  16.  20.  25.]]


In [12]:
poly2 = PolynomialFeatures(interaction_only=True)
poly2.fit(X)
print poly2
print poly2.transform(X)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=True)
[[  1.   0.   1.   0.]
 [  1.   2.   3.   6.]
 [  1.   4.   5.  20.]]


In [13]:
poly3 = PolynomialFeatures(include_bias=False)
poly3.fit(X)
print poly3
print poly3.transform(X)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
[[  0.   1.   0.   0.   1.]
 [  2.   3.   4.   6.   9.]
 [  4.   5.  16.  20.  25.]]
