In [108]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold,SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingClassifier

In [84]:
X = np.array([
    [0, 2, 0, 3],
    [0, 1, 4, 3],
    [0.1, 1, 1, 3]
], dtype=np.float64)
Y = np.array([1,2,1])

In [85]:
variance = VarianceThreshold(threshold=0.1)
print variance
variance.fit(X)
print variance.transform(X)

VarianceThreshold(threshold=0.1)
[[ 2.  0.]
 [ 1.  4.]
 [ 1.  1.]]


In [86]:
sk1 = SelectKBest(f_regression, k=2)
sk1.fit(X, Y)
print sk1
print sk1.scores_
print sk1.transform(X)

SelectKBest(k=2, score_func=<function f_regression at 0x000000000A8A4BA8>)
[  0.33333333   0.33333333  16.33333333          nan]
[[ 2.  0.]
 [ 1.  4.]
 [ 1.  1.]]


In [87]:
sk2 = SelectKBest(chi2, k=2)
sk2.fit(X, Y)
print sk2
print sk2.scores_
print sk2.transform(X)

SelectKBest(k=2, score_func=<function chi2 at 0x000000000A8A4B38>)
[ 0.05   0.125  4.9    0.   ]
[[ 2.  0.]
 [ 1.  4.]
 [ 1.  1.]]


In [88]:
estimator = SVR(kernel='linear')
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X, Y)
print selector.support_
print selector.n_features_
print selector.ranking_
print selector.transform(X)

[False  True  True False]
2
[2 1 1 3]
[[ 2.  0.]
 [ 1.  4.]
 [ 1.  1.]]


In [111]:
X2 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
Y2 = np.array([0, 0, 2, 2])
estimator = LogisticRegression(penalty='l1', C=0.1)
sfm = SelectFromModel(estimator)
sfm.fit(X2, Y2)
print sfm.transform(X2)

[[ 5.1]
 [ 4.9]
 [-6.2]
 [-5.9]]


In [112]:
X2 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
Y2 = np.array([0, 0, 2, 2])
estimator = GradientBoostingClassifier()
sfm = SelectFromModel(estimator)
sfm.fit(X2, Y2)
print sfm.transform(X2)

[[ 5.1  0.2]
 [ 4.9  0.2]
 [-6.2  2.3]
 [-5.9  1.8]]


In [122]:
from sklearn.decomposition import PCA
X2 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
pca = PCA(n_components=2)
pca.fit(X2)
print pca.mean_
print pca.components_
print pca.transform(X2)

[-0.525  1.725  3.325  1.125]
[[-0.90319637 -0.24920124  0.31484024  0.15169269]
 [ 0.03919747 -0.80616444 -0.27357029 -0.52318424]]
[[-6.26919501 -0.19988789]
 [-5.96395512  0.19535484]
 [ 6.28736349 -0.33667759]
 [ 5.94578665  0.34121064]]


In [133]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
X2 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
Y2 = np.array([0, 0, 2, 2])
lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(X2, Y2)
print lda.transform(X2)

[[-27.18468036]
 [-25.44008732]
 [ 26.80136112]
 [ 25.82340656]]
