In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

## Series:通过一维数组创建

In [7]:
arr=np.array([1.1,2,3,4])
series1=Series(arr)
series1

0    1.1
1    2.0
2    3.0
3    4.0
dtype: float64

In [8]:
series1.values

array([ 1.1,  2. ,  3. ,  4. ])

In [9]:
series1.index   #[0,len(arr)-1,1]

RangeIndex(start=0, stop=4, step=1)

In [10]:
arr1=Series([10,20,30,40])
arr1

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
arr1.index=[u'一',u'二',u'三',u'四']
arr1

一    10
二    20
三    30
四    40
dtype: int64

In [13]:
arr2=Series([99,98,0,100],index=[u'一',u'二',u'三',u'四'])
arr2

一     99
二     98
三      0
四    100
dtype: int64

In [11]:
##通过一维数组创建时，可以在创建的同时自定义索引值，也可以之后通过赋值的形式去修改

In [12]:
##通过字典创建

In [14]:
dict={'a':1,'b':2,'c':3,'d':4}
ser=Series(dict)
ser                           ##字典的键对应索引，值对应数据

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
ser.index

Index([u'a', u'b', u'c', u'd'], dtype='object')

In [16]:
ser.values

array([1, 2, 3, 4], dtype=int64)

In [19]:
arr2=Series([99,98,0,100],index=[u'一',u'一',u'三',u'四'])
arr2
arr2[0]

99

In [21]:
arr2[u'一']

一    99
一    98
dtype: int64

In [22]:
a1=Series(arr)
a1

0    1.1
1    2.0
2    3.0
3    4.0
dtype: float64

In [23]:
a1.index=['a','a','a','a']
a1

a    1.1
a    2.0
a    3.0
a    4.0
dtype: float64

In [25]:
a1[0]

1.1000000000000001

In [26]:
series=Series({'a':100,'b':200,'c':300})
series


a    100
b    200
c    300
dtype: int64

In [27]:
series[series>100]

b    200
c    300
dtype: int64

In [28]:
series/100  ##series中元素级别的运算结果，包含有索引值，并且键值关系不变

a    1.0
b    2.0
c    3.0
dtype: float64

In [29]:
series=Series([-1,-2,-3,-4])
series

0   -1
1   -2
2   -3
3   -4
dtype: int64

In [30]:
np.abs(series)   ##numpy中的通用函数在Series当中也是支持的

0    1
1    2
2    3
3    4
dtype: int64

In [31]:
scores=Series({'a':88,'b':99,'c':80,'d':78})
scores

a    88
b    99
c    80
d    78
dtype: int64

In [32]:
new=['a','b','ee','c','d']

In [51]:
scores1=Series(scores,index=new)
scores1

a     88.0
b     99.0
ee     NaN
c     80.0
d     78.0
dtype: float64

In [52]:
pd.isnull(scores1)   #值是NaN，返回True

a     False
b     False
ee     True
c     False
d     False
dtype: bool

In [53]:
pd.notnull(scores1)   #值不是NaN，返回True

a      True
b      True
ee    False
c      True
d      True
dtype: bool

In [54]:
scores1[pd.isnull(scores1)]

ee   NaN
dtype: float64

In [55]:
scores1[pd.notnull(scores1)]

a    88.0
b    99.0
c    80.0
d    78.0
dtype: float64

In [57]:
s1=Series([1,2,3],index=['a','b','c'])

In [58]:
s2=Series([10,20,30,40],index=['b','a','c','d'])

In [59]:
s1+s2

a    21.0
b    12.0
c    33.0
d     NaN
dtype: float64

In [60]:
s1*s2

a    20.0
b    20.0
c    90.0
d     NaN
dtype: float64

## name属性

In [33]:
s1=Series([1,2,3],index=['a','b','c'])

In [34]:
s1

a    1
b    2
c    3
dtype: int64

In [35]:
s1.name=u'价格'    #数据名称标签

In [36]:
s1.index.name=u'产品'   #索引名称标签

In [37]:
s1

产品
a    1
b    2
c    3
Name: 价格, dtype: int64

## DataFrame:通过二维数组创建

In [38]:
df=DataFrame([['a','b','c','d'],[1,2,3,4]])
df

0  1  2  3
0  a  b  c  d
1  1  2  3  4

In [39]:
arr=np.array([
        [1,2,3,4],
        [2,3,4,5],
        [3,4,5,6]
    ])

In [76]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [77]:
df=DataFrame(arr,index=['one','two','three'],columns=['a','b','c','d'])

In [78]:
df

a  b  c  d
one    1  2  3  4
two    2  3  4  5
three  3  4  5  6

In [79]:
df.index

Index(['one', 'two', 'three'], dtype='object')

In [80]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [81]:
df.values

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [43]:
dict1={'apart':['101','102','101'],
      'profits':[1000,2000,3000],
       'year':[2001,2010,2010],
       'month':8
      }

In [44]:
df=DataFrame(dict1)

In [45]:
df

apart  month  profits  year
0   101      8     1000  2001
1   102      8     2000  2010
2   101      8     3000  2010

In [46]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [47]:
df.columns

Index([u'apart', u'month', u'profits', u'year'], dtype='object')

In [48]:
df.values

array([['101', 8L, 1000L, 2001L],
       ['102', 8L, 2000L, 2010L],
       ['101', 8L, 3000L, 2010L]], dtype=object)

In [49]:
df.index=['one','two','three']
df

apart  month  profits  year
one     101      8     1000  2001
two     102      8     2000  2010
three   101      8     3000  2010

In [50]:
df=pd.read_csv("data1.csv")
df

name  age  source
0  gerry   18    98.5
1    tom   21    78.2
2   lili   24    98.5
3   john   20    89.2

In [51]:
# help(pd.read_csv)

In [52]:
df=DataFrame([
        ['Tom',np.NaN,456.67,'M'],['Merry',34,456.67,np.NaN],
        ['Gerry',np.NaN,np.NaN,np.NaN],['John',23,np.NaN,'M'],
        ['Joe',18,2300,'F']],columns=['name','age','salary','Gender']
    )

In [53]:
df

name   age   salary Gender
0    Tom   NaN   456.67      M
1  Merry  34.0   456.67    NaN
2  Gerry   NaN      NaN    NaN
3   John  23.0      NaN      M
4    Joe  18.0  2300.00      F

In [54]:
df.isnull()

name    age salary Gender
0  False   True  False  False
1  False  False  False   True
2  False   True   True   True
3  False  False   True  False
4  False  False  False  False

In [57]:
df.notnull()

name    age salary Gender
0  True  False   True   True
1  True   True   True  False
2  True  False  False  False
3  True   True  False   True
4  True   True   True   True

In [66]:
df.dropna()   #dropna删除包含nan值的行数据

name   age  salary Gender
4  Joe  18.0  2300.0      F

In [67]:
df.dropna(how='all')   #丢弃全部为NaN值的行数据

name   age   salary Gender
0    Tom   NaN   456.67      M
1  Merry  34.0   456.67    NaN
2  Gerry   NaN      NaN    NaN
3   John  23.0      NaN      M
4    Joe  18.0  2300.00      F

In [68]:
df.dropna(axis=1)   #dropna删除包含nan值的列数据

name
0    Tom
1  Merry
2  Gerry
3   John
4    Joe

In [69]:
df

name   age   salary Gender
0    Tom   NaN   456.67      M
1  Merry  34.0   456.67    NaN
2  Gerry   NaN      NaN    NaN
3   John  23.0      NaN      M
4    Joe  18.0  2300.00      F