In [18]:
import tensorflow as tf
# 创建两个变量
tf.reset_default_graph()  
v1= tf.Variable(tf.random_normal([1, 2], stddev=0.35), name="v1")
v2= tf.Variable(tf.zeros([1,2]), name="v2")

# 添加用于初始化变量的节点
init_op = tf.global_variables_initializer()

# Create a saver.
saver = tf.train.Saver(tf.global_variables())

# 运行图，打开会话，每1000次保存一个模型
sess = tf.Session()
step = 1000
sess.run(init_op)
saver.save(sess, './save/my-model', global_step=step)
print(sess.run('v1:0'))
print(sess.run('v2:0'))

[[0.26730978 0.10170209]]
[[0. 0.]]


In [19]:
import tensorflow as tf
with tf.Session() as sess:    
    saver = tf.train.import_meta_graph('./save/my-model-1000.meta')
    module_file = tf.train.latest_checkpoint('./save')
    print('latest_model:', module_file)
    saver.restore(sess, module_file)
#     saver.restore(sess,tf.train.latest_checkpoint('./save'))
    print(sess.run('v1:0'))
    print(sess.run('v2:0'))

latest_model: ./save\my-model-1000
INFO:tensorflow:Restoring parameters from ./save\my-model-1000
[[0.26730978 0.10170209]]
[[0. 0.]]


In [20]:
import tensorflow as tf
with tf.Session() as sess:    
    saver = tf.train.import_meta_graph('./save/my-model-1000.meta')
    module_file = tf.train.latest_checkpoint('./save')
    print('latest_model:', module_file)
    saver.restore(sess, module_file)
#     saver.restore(sess,tf.train.latest_checkpoint('./save'))
    print(sess.run('v1:0'))

latest_model: ./save\my-model-1000
INFO:tensorflow:Restoring parameters from ./save\my-model-1000
[[0.26730978 0.10170209]]
